name: Post the screenshots into a comment from Peek Icons workflow
on:
  workflow_run:
    workflows: ["Peek Icons"]
    types: 
      - completed
jobs: 
  post_screenshots_in_comment:
    name: Post the screenshot
    runs-on: ubuntu-18.04
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.11.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: peek_icons.yml
          run_id: ${{ github.event.workflow_run.id }}
      - run: cat ./pr_num/pr_num.txt
        if: always()
      # - name: Upload screenshot of the newly made icons
      #   id: icons_overview_img_step
      #   uses: devicons/public-upload-to-imgur@v2.1
      #   if: success()
      #   with:
      #     path: ./screenshots/new_icons.png
      #     client_id: ${{secrets.IMGUR_CLIENT_ID}}
      # - name: Upload zoomed in screenshot of the newly made icons
      #   id: icons_detailed_img_step
      #   uses: devicons/public-upload-to-imgur@v2.1
      #   if: success()
      #   with:
      #     path: ./screenshots/screenshot_*.png
      #     client_id: ${{secrets.IMGUR_CLIENT_ID}}
      # - name: Generate the markdowns for the screenshot and put it in the DETAILED_IMGS_MARKDOWN env var
      #   if: success()
      #   env:  # need to set IMG_URLS for script to work
      #     IMG_URLS: ${{ steps.icons_detailed_img_step.outputs.imgur_urls }}
      #   shell: bash
      #   run: |   
      #     echo 'DETAILED_IMGS_MARKDOWN<<EOF' >> $GITHUB_ENV
      #     python ../.github/scripts/generate_screenshot_markdown.py >> $GITHUB_ENV
      #     echo 'EOF' >> $GITHUB_ENV
      - name: Create comment
        uses: jungwinter/comment@v1 # let us comment on a specific PR
        id: create
        if: success()
        env:
          # OVERVIEW_IMG_URL: ${{ fromJSON(steps.icons_overview_img_step.outputs.imgur_urls)[0] }}
          MESSAGE: hi
        with:
          type: create
          body: ${{ env.MESSAGE }}
          issue_number: 31
          token: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     message: ${{format(env.MESSAGE, env.OVERVIEW_IMG_URL, env.DETAILED_IMGS_MARKDOWN)}}
      # - name: Comment on the PR about the result
      #   if: failure()
      #   uses: NejcZdovc/comment-pr@v1.1.1
      #   env:
      #     MESSAGE: |
      #       Hi!

      #       I'm Devicons' Peek Bot and it seems we've ran into a problem. I'm supposed to check your svgs but I couldn't do my task due to an issue.

      #       Can you please double check and fix the possible issues below:

      #       - Your svgs are named and added correctly to the /icons folder as seen [here](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#orgGuidelines).
      #       - Your icon information has been added to the `devicon.json` as seen [here](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#updateDevicon)
      #       - Your PR title follows the format seen [here](https://github.com/devicons/devicon/blob/master/CONTRIBUTING.md#overview)

      #       Once everything is fixed, the maintainers will try again. If I still fail, the maintainers will investigate what cause this problem. 

      #       Thank you for your help :smile:

      #       Cheers :),
      
      #       Peek Bot
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     message: ${{env.MESSAGE}}
