name: Test
on: push
jobs: 
  post_screenshots_in_comment:
    name: Post the screenshot
    runs-on: ubuntu-18.04
    env: 
      SVG_ERR_MSGS: '[testingicon-original.svg:n-contains style declaration using fill - classes with the fill attribute instead, testingicon-plain.svg:n-contains style declaration using fill - classes with the fill attribute instead, testingicon2-original.svg:n-contains style declaration using fill - classes with the fill attribute instead, testingicon2-plain.svg:n-contains style declaration using fill - classes with the fill attribute instead]'
    steps:
      - name: confirm
        env: 
          JSON: env.SVG_ERR_MSGS
          STR: fromJSON(env.SVG_ERR_MSGS)[0]
          FORMATTED_MSGS: ${{ join(fromJSON(env.SVG_ERR_MSGS), '\n\n') }}
        run: |
          echo $JSON
          echo $STR
          echo $FORMATTED_MSGS